theme: jekyll-theme-slate
title: [Cooperative Aerial-Ground Multi-Robot System for Automated Construction Tasks]
description: [Marko Krizmancic, Barbara Arbanas, Tamara Petrovic, Frano Petric and Stjepan Bogdan]
